version: '3'

services:
  app:
    image: php:8.2-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=optimizeit"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=toor"

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_ROOT_PASSWORD=secret"

networks:
  laravel:
